### ISSUE TITLE
Can I input my own DESeq outputs into your package?

### ISSUE THREAD

**Issue by JaniceGoh93** [WTaoUMC/RegEnrich#1]
Hi, i am trying to use your package to find out which transcription factors are significant in my dataset. I am really excited about this package, and it is exactly what I have been looking for. I have a somewhat more complicated experimental design and was wondering if there is a way for me to bypass the differential expression analysis and feed in a list of genes and fold changes instead. Thanks!

**Comment by WTaoUMC** [comment]
I am posting the email that I replied to the asker in case others have the same question.
------
Hi,
 
Thanks for your interest in our work. Yes, it is possible to bypass the differential expression analysis step.
 
Take the “Examples” section of regenrich_diffExpr function help page as an example:
 
# library(RegEnrich)
data("Lyme_GSE63085")
data("TFs")
 
data = log2(Lyme_GSE63085$FPKM + 1)
colData = Lyme_GSE63085$sampleInfo
 
# Take first 2000 rows for example
data1 = data[seq(2000), ]
 
design = model.matrix(~0 + patientID + week, data = colData)
 
# Initializing a 'RegenrichSet' object
object = RegenrichSet(expr = data1,
                      colData = colData,
                      method = 'limma', minMeanExpr = 0,
                      design = design,
                      contrast = c(rep(0, ncol(design) - 1), 1),
                      networkConstruction = 'COEN',
                      enrichTest = 'FET')
 
object
 
# Obtain the default p value and logFC and assign to x
x = mcols(object)
 
# Change the p value and logFC according to your data
x$p = runif(nrow(x)) # use your own data, the p values must correspond to the genes
x$logFC = rnorm(nrow(x)) # use your own data, the logFC values must correspond to the genes
 
# assign object with updated p values and logFC
mcols(object) = x
 
object
 
Good luck!
Best,
Weiyang Tao
