### ISSUE TITLE
Problems with the vignette

### ISSUE THREAD

**Issue by josruirod** [WTaoUMC/RegEnrich#2]
HI, I'm trying to use your package following the vigenette. Howver, in the last step, regenrich_rankscore, I'm getting the error:

> Error in get(x, envir = ns, inherits = FALSE) : 
  object 'print.tbl' not found

Any ideas? This is a brand new R installation (4.0.3). 
Thanks for the support

**Comment by WTaoUMC** [comment]
Hi,

Did you successfully install the tibble package, which is required by RegEnrich?
If not, please install it first and then try to run the example in the help page of regenrich_rankScore function.

If it still does not work, could you please show me the results of sessionInfo() for me?

Best,
Weiyang

**Comment by josruirod** [comment]
Hi, thanks for the answer and the support.
Yes, I'd say it's properly installed. I'm showing you the sessionInfo:

Any ideas?

> sessionInfo()
> R version 4.0.4 (2021-02-15)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 20.04.2 LTS
> 
> Matrix products: default
> BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=es_ES.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=es_ES.UTF-8   
>  [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=es_ES.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=es_ES.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] RegEnrich_1.0.0             SummarizedExperiment_1.20.0 Biobase_2.50.0              GenomicRanges_1.42.0       
>  [5] GenomeInfoDb_1.26.2         IRanges_2.24.1              MatrixGenerics_1.2.1        matrixStats_0.58.0         
>  [9] BiocSet_1.4.0               tibble_3.1.0                dplyr_1.0.4                 S4Vectors_0.28.1           
> [13] BiocGenerics_0.36.0        
> 
> loaded via a namespace (and not attached):
>   [1] fgsea_1.16.0           colorspace_2.0-0       ellipsis_0.3.1         dynamicTreeCut_1.63-1  qvalue_2.22.0         
>   [6] htmlTable_2.1.0        XVector_0.30.0         base64enc_0.1-3        rstudioapi_0.13        bit64_4.0.5           
>  [11] AnnotationDbi_1.52.0   fansi_0.4.2            codetools_0.2-18       splines_4.0.4          doParallel_1.0.16     
>  [16] cachem_1.0.4           GOSemSim_2.16.1        impute_1.64.0          geneplotter_1.68.0     knitr_1.31            
>  [21] Formula_1.2-4          annotate_1.68.0        WGCNA_1.69             cluster_2.1.1          GO.db_3.12.1          
>  [26] png_0.1-7              compiler_4.0.4         httr_1.4.2             backports_1.2.1        assertthat_0.2.1      
>  [31] Matrix_1.3-2           fastmap_1.1.0          ontologyIndex_2.7      limma_3.46.0           cli_2.3.1             
>  [36] htmltools_0.5.1.1      tools_4.0.4            gtable_0.3.0           glue_1.4.2             GenomeInfoDbData_1.2.4
>  [41] reshape2_1.4.4         DO.db_2.9              tinytex_0.29           fastmatch_1.1-0        Rcpp_1.0.6            
>  [46] vctrs_0.3.6            Biostrings_2.58.0      preprocessCore_1.52.1  iterators_1.0.13       xfun_0.21             
>  [51] fastcluster_1.1.25     stringr_1.4.0          lifecycle_1.0.0        XML_3.99-0.5           DOSE_3.16.0           
>  [56] zlibbioc_1.36.0        scales_1.1.1           RColorBrewer_1.1-2     memoise_2.0.0          gridExtra_2.3         
>  [61] ggplot2_3.3.3          rpart_4.1-15           latticeExtra_0.6-29    stringi_1.5.3          RSQLite_2.2.3         
>  [66] genefilter_1.72.1      BiocIO_1.0.1           foreach_1.5.1          randomForest_4.6-14    checkmate_2.0.0       
>  [71] BiocParallel_1.24.1    rlang_0.4.10           pkgconfig_2.0.3        bitops_1.0-6           lattice_0.20-41       
>  [76] purrr_0.3.4            htmlwidgets_1.5.3      bit_4.0.4              tidyselect_1.1.0       plyr_1.8.6            
>  [81] magrittr_2.0.1         DESeq2_1.30.1          R6_2.5.0               generics_0.1.0         Hmisc_4.4-2           
>  [86] DelayedArray_0.16.1    DBI_1.1.1              pillar_1.5.0           foreign_0.8-81         survival_3.2-7        
>  [91] KEGGREST_1.30.1        RCurl_1.98-1.2         nnet_7.3-15            crayon_1.4.1           utf8_1.1.4            
>  [96] jpeg_0.1-8.1           locfit_1.5-9.4         grid_4.0.4             data.table_1.14.0      blob_1.2.1            
> [101] digest_0.6.27          xtable_1.8-4           tidyr_1.1.2            munsell_0.5.0

**Comment by WTaoUMC** [comment]
Hi,

Thanks for the information. It is because of tibble_3.1.0 does not have print.tbl function. But tibble_3.0.3 does have.

I will debug it and update RegEnrich on Bioconductor in the next release. But, currently, you can solve the problem by:

library(devtools)
install_version("tibble", version = "3.0.3", repos = "http://cran.us.r-project.org")

Good luck!
Best,
Weiyang

**Comment by WTaoUMC** [comment]
Hi, Thanks for the information. It is because tibble_3.1.0 does not have the print.tbl function. But tibble_3.0.3 does have.
I have now updated the RegEnrich. It should not have the same bug. Good luck!

**Comment by josruirod** [comment]
Hi, I can confirm the bug is now gone. Thanks for the support
